using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using Sirenix.OdinInspector;

public class RoomInformation : MonoBehaviour
{
    [FoldoutGroup("ª«¥ó³]žm")]
    public TMP_Text no_text;
    [FoldoutGroup("ª«¥ó³]žm")]
    public TMP_Text roomName_text;
    [FoldoutGroup("ª«¥ó³]žm")]
    public TMP_Text curremtTopic_text;
    [FoldoutGroup("ª«¥ó³]žm")]
    public TMP_Text teacherName_text;
    [FoldoutGroup("ª«¥ó³]žm")]
    public TMP_Text memberNum_text;

    [FoldoutGroup("°ÑŒÆ³]žm")]
    public int no;
    [FoldoutGroup("°ÑŒÆ³]žm")]
    public string roomName;
    [FoldoutGroup("°ÑŒÆ³]žm")]
    public string curremtTopic;
    [FoldoutGroup("°ÑŒÆ³]žm")]
    public string teacherName;
    [FoldoutGroup("°ÑŒÆ³]žm")]
    public int playerCount;
    [FoldoutGroup("°ÑŒÆ³]žm")]
    public int maxPlayers;

    private void FixedUpdate()
    {
        no_text.text = no.ToString();
        roomName_text.text = roomName;

        if (curremtTopic != string.Empty)
        {
            curremtTopic_text.text = curremtTopic;
        }
        else
        {
            curremtTopic_text.text = "No Topic Selected.";
        }
        
        teacherName_text.text = teacherName;
        memberNum_text.text = playerCount.ToString() + "/" + maxPlayers.ToString();
    }

}
