using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using Sirenix.OdinInspector;

public class InfoCanvasUI : MonoBehaviour
{
    [FoldoutGroup("ª«¥ó³]žm")]
    public StarMapController starMapController;
    [FoldoutGroup("ª«¥ó³]žm")]
    [BoxGroup("ª«¥ó³]žm/Date")]
    public Text year;
    [BoxGroup("ª«¥ó³]žm/Date")]
    public Text month;
    [BoxGroup("ª«¥ó³]žm/Date")]
    public Text day;
    [BoxGroup("ª«¥ó³]žm/Date")]
    public Text hour;

    [BoxGroup("ª«¥ó³]žm/location")]
    public Text longitude;
    [BoxGroup("ª«¥ó³]žm/location")]
    public Text latitude;
    

    private void Update()
    {
        Vector3 rot = new Vector3(0, Camera.main.transform.rotation.eulerAngles.y, 0);
        transform.rotation = Quaternion.Lerp(transform.rotation, Quaternion.Euler(rot), 10 * Time.deltaTime);

        year.text = starMapController.starMapControlData.dateTime.Year.ToString();
        month.text = starMapController.starMapControlData.dateTime.Month.ToString();
        day.text = starMapController.starMapControlData.dateTime.Day.ToString();
        hour.text = starMapController.starMapControlData.dateTime.Hour.ToString();

        longitude.text = starMapController.starMapControlData.longitude.ToString(); //žg«×
        latitude.text = starMapController.starMapControlData.latitude.ToString(); //œn«×
    }

}
